name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Tag and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${VERSION}
          git push origin v${VERSION}
